name: PR Risk Checker

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-risk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug Token Present
        run: |
          if [ -z "${{ secrets.GH_PAT }}" ]; then
            echo "GH_PAT is EMPTY or not set"
          else
            echo "GH_PAT is present"
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r Code_Review_Analytics/requirements.txt

      - name: Run PR Risk Checker
        id: riskcheck
        continue-on-error: true
        run: |
          echo "Running PR Risk Checker..."

          output=$(python3 -m pr_risk_checker.cli \
            --repo_owner ${{ github.repository_owner }} \
            --repo_name ${{ github.event.repository.name }} \
            --pr_number ${{ github.event.pull_request.number }})

          echo "$output"

          # Extract is_risky value from the output
          is_risky=$(echo "$output" | grep -oP 'is_risky=\K(true|false)')
          echo "is_risky=$is_risky" >> "$GITHUB_OUTPUT"
        working-directory: Code_Review_Analytics
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Print PR Risk Status
        run: echo "PR is risky? ${{ steps.riskcheck.outputs.is_risky }}"

      - name: Debug riskcheck output
        run: |
          echo "Debug - Output from riskcheck step:"
          echo "IS_RISKY=${{ steps.riskcheck.outputs.is_risky }}"

      - name: Assign reviewer if risky
        if: steps.riskcheck.outputs.is_risky == 'true'
        run: |
          python pr_risk_checker/assign_reviewer.py
        working-directory: Code_Review_Analytics
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          REVIEWERS: "senior1,senior2,senior3"  # Replace with actual GitHub username
